#!/bin/bash

################-> are comments
################-> "#PBS" are Batch Script commands

#PBS -m abe

################ Verbose mode

#PBS -V

################

################ Change these parameters according to your requisites

#PBS -l nodes=1:ppn=32:cluster-Atlantica,walltime=3:00:00

################ Where:
################ nodes = number of nodes requested
################ ppn = number of cores per node
################ cluster-Atlantica / cluster-Gates = cluster name
################ walltime = max allocation time

################ Please, change this e-mail address to yours

#PBS -M raphael.baldi@acad.pucrs.br

################

#PBS -r n

################ Output options

#PBS -j oe

################

################ Please, change this directory to your working dir.

#PBS -d /home/pp12825/tp01

################

################
echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo `cat $PBS_NODEFILE | uniq`
echo
echo JOB_ID:
echo `echo $PBS_JOBID`
echo ################

############# Command example

/home/pp12825/tp01/gameoflife random 5000 5000 1000 1 0
/home/pp12825/tp01/gameoflife random 5000 5000 1000 2 0
/home/pp12825/tp01/gameoflife random 5000 5000 1000 4 0
/home/pp12825/tp01/gameoflife random 5000 5000 1000 8 0
/home/pp12825/tp01/gameoflife random 5000 5000 1000 16 0
/home/pp12825/tp01/gameoflife random 5000 5000 1000 32 0

################

echo Final Time is `date`
